import { ExpertReviewQueue } from "@/components/ExpertReviewQueue";

export const metadata = {
  title: "Expert Review — Dot Lens",
  description: "Review and approve AI-generated tactile materials before they reach students.",
};

export default function ExpertReviewPage() {
  return (
    <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6">
      <div className="mb-8 border-b border-line pb-6">
        <p className="eyebrow">Expert · Review Mode</p>
        <h1 className="mt-2 text-balance text-3xl font-semibold text-ink sm:text-4xl">
          Expert Review Queue
        </h1>
        <p className="mt-2 max-w-2xl text-[15px] leading-relaxed text-muted">
          AI가 생성한 촉각 자료를 검토하고 승인, 수정 요청, 반려 처리합니다.
        </p>
        <p className="mt-1 max-w-2xl text-[14px] text-muted">
          Review tactile materials generated by AI. Approve quality content, request revisions, or reject materials that don&apos;t meet standards.
        </p>
      </div>

      {/* Role context */}
      <div className="mb-6 flex flex-wrap gap-3">
        <div className="rounded-xl border border-line bg-surface px-4 py-2.5 shadow-card">
          <p className="text-[11px] font-semibold uppercase tracking-eyebrow text-muted">Current Role</p>
          <p className="mt-0.5 text-[14px] font-semibold text-ink">Expert Reviewer</p>
        </div>
        <div className="rounded-xl border border-line bg-surface px-4 py-2.5 shadow-card">
          <p className="text-[11px] font-semibold uppercase tracking-eyebrow text-muted">Criteria</p>
          <p className="mt-0.5 text-[13px] text-muted">Clarity · Tactile Readability · Educational Accuracy</p>
        </div>
      </div>

      <ExpertReviewQueue />
    </div>
  );
}
